name: Python Pull Request Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:


  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
        #continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
